sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t sonstein/react -f Dockerfile.dev

script:
  - docker run -e CI=true sonstein/react npm run test -- --coverage

after_success:
  - echo "Test Success"
